In [175]:
import pandas as pd 
import copy

In [176]:
df_1 = pd.read_csv("../data/Drug_effects.csv")
df_2 = pd.read_csv("../data/patient_records.csv")
df_3 = pd.read_csv("../data/medicine_dataset.csv")

In [177]:
df_main = pd.merge(df_2, df_1, left_on='Patient ID', right_on='PatientId')
df_main = pd.merge(df_main, df_3, left_on='drugId', right_on='id')

In [178]:
df_main.head()

Patient ID              Name  Age  Gender  Height(cm)  Weight(lb)  \
0           0  Susan Sanchez MD   72    Male         186         115   
1           1     Cheryl Farley   22  Female         184         203   
2           2     Rhonda Waters   22  Female         173         164   
3           3   Nicolas Proctor   48    Male         173         121   
4           4    Misty Phillips   41    Male         185         216   

  Pregnancy Blood Group Past Medical Conditions                       _id  \
0        No          A+                 Asthama  65d1982ee0967ad93d3514cd   
1       Yes          B+                 Asthama  65d1982ee0967ad93d3514ce   
2       Yes          O+        Diabetes(type 1)  65d1982ee0967ad93d3514cf   
3        No          B+            Hypertension  65d1982ee0967ad93d3514d0   
4        No          O-            Hypertension  65d1982ee0967ad93d3514d1   

   ...            substitute3              substitute4 sideEffect0  \
0  ...     Fightox 625 Tablet  Novamox CV 625mg Tablet    Vomiting   
1  ...  Cazithro 500mg Tablet    Trulimax 500mg Tablet    Vomiting   
2  ...         Capex LS Syrup          Broxum LS Syrup      Nausea   
3  ...    Fexise 120mg Tablet     Histafree 120 Tablet    Headache   
4  ...                    NaN                      NaN  Sleepiness   

        sideEffect1     sideEffect2    sideEffect3   sideEffect4  \
0            Nausea        Diarrhea            NaN           NaN   
1            Nausea  Abdominal pain       Diarrhea           NaN   
2          Vomiting        Diarrhea  Upset stomach  Stomach pain   
3        Drowsiness       Dizziness         Nausea           NaN   
4  Dryness in mouth             NaN            NaN           NaN   

                                        treatment_of  \
0                  Treatment of Bacterial infections   
1                  Treatment of Bacterial infections   
2                      Treatment of Cough with mucus   
3  Treatment of Sneezing and runny nose due to al...   
4                   Treatment of Allergic conditions   

               Chemical Class Habit Forming  
0                         NaN            No  
1                  Macrolides            No  
2                         NaN            No  
3  Diphenylmethane Derivative            No  
4       Pyridines Derivatives            No  

[5 rows x 28 columns]

In [179]:
df_main.columns

Index(['Patient ID', 'Name', 'Age', 'Gender', 'Height(cm)', 'Weight(lb)',
       'Pregnancy', 'Blood Group', 'Past Medical Conditions', '_id', 'drugId',
       'PatientId', 'side_effect', 'id', 'name', 'substitute0', 'substitute1',
       'substitute2', 'substitute3', 'substitute4', 'sideEffect0',
       'sideEffect1', 'sideEffect2', 'sideEffect3', 'sideEffect4',
       'treatment_of', 'Chemical Class', 'Habit Forming'],
      dtype='object')

In [180]:
df_new = df_main[['Past Medical Conditions', 'name', 'side_effect' ]] #'Age', 'Gender', 'Height(cm)', 'Weight(lb)', 'Pregnancy', 'Blood Group', 

In [181]:
df_new = df_new.fillna("No Side Effect")

In [182]:
df_new.head()

Past Medical Conditions                      name       side_effect
0                 Asthama  augmentin 625 duo tablet    No Side Effect
1                 Asthama       azithral 500 tablet    No Side Effect
2        Diabetes(type 1)          ascoril ls syrup     Upset stomach
3            Hypertension      allegra 120mg tablet    No Side Effect
4            Hypertension            avil 25 tablet  Dryness in mouth

In [183]:
df = copy.deepcopy(df_new)

In [186]:
medical_encoded = pd.get_dummies(df['Past Medical Conditions'])
name_encoded = pd.get_dummies(df['name'])

In [187]:
df = pd.concat([df, medical_encoded], axis=1)

In [188]:
df = pd.concat([df, name_encoded], axis=1)

In [189]:
df.head()

Past Medical Conditions                      name       side_effect   Acne  \
0                 Asthama  augmentin 625 duo tablet    No Side Effect  False   
1                 Asthama       azithral 500 tablet    No Side Effect  False   
2        Diabetes(type 1)          ascoril ls syrup     Upset stomach  False   
3            Hypertension      allegra 120mg tablet    No Side Effect  False   
4            Hypertension            avil 25 tablet  Dryness in mouth  False   

   Allergies  Asthama  Cancer  Colds & Flu  Covid19  Depression  ...  \
0      False     True   False        False    False       False  ...   
1      False     True   False        False    False       False  ...   
2      False    False   False        False    False       False  ...   
3      False    False   False        False    False       False  ...   
4      False    False   False        False    False       False  ...   

   augmentin 625 duo tablet  augmentin dds suspension  \
0                      True                     False   
1                     False                     False   
2                     False                     False   
3                     False                     False   
4                     False                     False   

   augmentin duo oral suspension  avil 25 tablet  avomine tablet  \
0                          False           False           False   
1                          False           False           False   
2                          False           False           False   
3                          False           False           False   
4                          False            True           False   

   axcer  90mg tablet  azee 500 tablet  azicip 500 tablet  \
0               False            False              False   
1               False            False              False   
2               False            False              False   
3               False            False              False   
4               False            False              False   

   azithral 200 liquid  azithral 500 tablet  
0                False                False  
1                False                 True  
2                False                False  
3                False                False  
4                False                False  

[5 rows x 65 columns]

In [190]:
df = df.replace({True: 1, False: 0})

C:\Users\anshu\AppData\Local\Temp\ipykernel_30492\3074727906.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace({True: 1, False: 0})


In [191]:
df

Past Medical Conditions                              name  \
0                    Asthama          augmentin 625 duo tablet   
1                    Asthama               azithral 500 tablet   
2           Diabetes(type 1)                  ascoril ls syrup   
3               Hypertension              allegra 120mg tablet   
4               Hypertension                    avil 25 tablet   
...                      ...                               ...   
1995                Hayfever          augmentin dds suspension   
1996                    Acne                 azicip 500 tablet   
1997             Colds & Flu               aldigesic-sp tablet   
1998              Depression         amoxycillin 500mg capsule   
1999                    Acne  asthakind expectorant sugar free   

            side_effect  Acne  Allergies  Asthama  Cancer  Colds & Flu  \
0        No Side Effect     0          0        1       0            0   
1        No Side Effect     0          0        1       0            0   
2         Upset stomach     0          0        0       0            0   
3        No Side Effect     0          0        0       0            0   
4      Dryness in mouth     0          0        0       0            0   
...                 ...   ...        ...      ...     ...          ...   
1995           Vomiting     0          0        0       0            0   
1996           Diarrhea     1          0        0       0            0   
1997           Vomiting     0          0        0       0            1   
1998  Allergic reaction     0          0        0       0            0   
1999           Diarrhea     1          0        0       0            0   

      Covid19  Depression  ...  augmentin 625 duo tablet  \
0           0           0  ...                         1   
1           0           0  ...                         0   
2           0           0  ...                         0   
3           0           0  ...                         0   
4           0           0  ...                         0   
...       ...         ...  ...                       ...   
1995        0           0  ...                         0   
1996        0           0  ...                         0   
1997        0           0  ...                         0   
1998        0           1  ...                         0   
1999        0           0  ...                         0   

      augmentin dds suspension  augmentin duo oral suspension  avil 25 tablet  \
0                            0                              0               0   
1                            0                              0               0   
2                            0                              0               0   
3                            0                              0               0   
4                            0                              0               1   
...                        ...                            ...             ...   
1995                         1                              0               0   
1996                         0                              0               0   
1997                         0                              0               0   
1998                         0                              0               0   
1999                         0                              0               0   

      avomine tablet  axcer  90mg tablet  azee 500 tablet  azicip 500 tablet  \
0                  0                   0                0                  0   
1                  0                   0                0                  0   
2                  0                   0                0                  0   
3                  0                   0                0                  0   
4                  0                   0                0                  0   
...              ...                 ...              ...                ...   
1995               0                   0                0            

In [192]:
df = df.drop(['Past Medical Conditions'], axis=1)

In [193]:
df = df.drop(['name'], axis=1)

In [194]:
df

side_effect  Acne  Allergies  Asthama  Cancer  Colds & Flu  \
0        No Side Effect     0          0        1       0            0   
1        No Side Effect     0          0        1       0            0   
2         Upset stomach     0          0        0       0            0   
3        No Side Effect     0          0        0       0            0   
4      Dryness in mouth     0          0        0       0            0   
...                 ...   ...        ...      ...     ...          ...   
1995           Vomiting     0          0        0       0            0   
1996           Diarrhea     1          0        0       0            0   
1997           Vomiting     0          0        0       0            1   
1998  Allergic reaction     0          0        0       0            0   
1999           Diarrhea     1          0        0       0            0   

      Covid19  Depression  Diabetes(type 1)  Diabetes(type 2)  ...  \
0           0           0                 0                 0  ...   
1           0           0                 0                 0  ...   
2           0           0                 1                 0  ...   
3           0           0                 0                 0  ...   
4           0           0                 0                 0  ...   
...       ...         ...               ...               ...  ...   
1995        0           0                 0                 0  ...   
1996        0           0                 0                 0  ...   
1997        0           0                 0                 0  ...   
1998        0           1                 0                 0  ...   
1999        0           0                 0                 0  ...   

      augmentin 625 duo tablet  augmentin dds suspension  \
0                            1                         0   
1                            0                         0   
2                            0                         0   
3                            0                         0   
4                            0                         0   
...                        ...                       ...   
1995                         0                         1   
1996                         0                         0   
1997                         0                         0   
1998                         0                         0   
1999                         0                         0   

      augmentin duo oral suspension  avil 25 tablet  avomine tablet  \
0                                 0               0               0   
1                                 0               0               0   
2                                 0               0               0   
3                                 0               0               0   
4                                 0               1               0   
...                             ...             ...             ...   
1995                              0               0               0   
1996                              0               0               0   
1997                              0               0               0   
1998                              0               0               0   
1999                              0               0               0   

      axcer  90mg tablet  azee 500 tablet  azicip 500 tablet  \
0                      0                0                  0   
1                      0                0                  0   
2                      0                0                  0   
3                      0                0                  0   
4                      0                0                  0   
...                  ...              ...                ...   
1995                   0                0                  0   
1996                   0                0                  1   
1997                   0                0                  0   
1998                   0                0                  0   
1999

In [195]:
X = df.drop(["side_effect"], axis = 1)

In [196]:
y = df["side_effect"]

In [197]:
from sklearn.model_selection import train_test_split
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [198]:
from sklearn.ensemble import RandomForestClassifier

In [199]:
# Initialize and train the model
model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

In [200]:
# Predict on the test set
y_pred = model.predict(X_test)

In [203]:
from sklearn.metrics import accuracy_score
# Evaluate model performance
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy (%):", accuracy * 100)

Accuracy (%): 82.25


In [204]:
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import confusion_matrix

In [205]:
conf_matrix = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[12  0  0 ...  0  0  0]
 [ 0  1  0 ...  0  0  0]
 [ 0  0  4 ...  0  0  0]
 ...
 [ 0  0  0 ...  8  1  0]
 [ 0  0  0 ...  0 30  0]
 [ 0  0  0 ...  0  0  3]]


In [206]:
y_pred

array(['No Side Effect', 'Dizziness', 'No Side Effect', 'Diarrhea',
       'Injection site reactions (pain, swelling, redness)',
       'Balance disorder (loss of balance)', 'No Side Effect', 'Vomiting',
       'Nausea', 'No Side Effect', 'Nausea', 'No Side Effect',
       'Drowsiness', 'Weakness', 'Upset stomach', 'Tachycardia',
       'Abdominal pain', 'Dryness in mouth', 'Abdominal pain', 'Vomiting',
       'Vomiting', 'Tremors', 'Sedation', 'No Side Effect', 'Flatulence',
       'Nausea', 'Drowsiness', 'Tremors', 'No Side Effect', 'Vomiting',
       'Headache', 'Diarrhea', 'Nausea', 'Abdominal pain', 'Drowsiness',
       'No Side Effect', 'Loss of appetite', 'Increased heart rate',
       'Flatulence', 'No Side Effect', 'Upset stomach', 'Vomiting',
       'Diarrhea', 'Tiredness', 'Drowsiness', 'Stomach pain',
       'Abdominal pain', 'Muscle pain', 'Palpitations', 'Nausea',
       'Sleepiness', 'Vomiting', 'Vomiting', 'No Side Effect',
       'No Side Effect', 'No Side Effect', 'Vo

In [207]:
import pickle

In [208]:
with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)